### ISSUE TITLE
Tricks and Comments

### ISSUE THREAD

**Issue by marue59** [marue59/snowTricks#7]
Create Entity and relation
Add Delete Update for Trick and Comment
Create front 

Difficulty level: 8
Estimation time for me : 10 days

**Comment by etokas** [comment]
Par contre oui 
La création des trick n’est pas terminé il faut:

- Ajouter l’ajout des videos / photos comme indiqué dans le wireframe 
- Permettre la modification des tricks 
- Suppression des pictures/videos
Ajout des commentaires depuis la page trick

Puis si tout est ok on fermera le issue

:)
